graph LR
A[Resources]
B[Class notes and slides]
C[Assignments and solutions]
D[Computer projects and solutions]
E[Review documents]
F[Previous midterms and solutions]
G[Practice final and solution]
H[Extra examples and solutions]
I[Combined examples and solutions]
J[Instructor support]
A --> B
A --> C
A --> D
A --> E
A --> F
A --> G
A --> H
A --> I
A --> J